name: 'Rice & Spice'
favicon: null
layout_spectrum: 0.24668
typography_spectrum: 0.34439
title: 'Rice & Spice Asian Deli'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFCFF'
    - '#AA41CF'
    - '#996FA3'
    - '#BD99C6'
    - '#72467B'
  brandStrength: 0.3125
  lightness: 0.6622899
  saturation: 0.7040783
  rhythmicContrast: 0.5648698
purpose: []
