layout_spectrum: 1
typography_spectrum: 0.702509
color:
  saturation: 0.7040783
  lightness: 0.6622899
  brandStrength: 0.5143369
  brandColors:
    - '#FFFCFF'
    - '#AA41CF'
    - '#996FA3'
    - '#BD99C6'
    - '#72467B'
  rhythmicContrast: 0.5648698
name: Rice and Spice
